# Mousai: An Open-Source General Purpose Harmonic Balance Solver

Joseph C. Slater, October 23, 2017

In [54]:
%matplotlib inline
%load_ext autoreload
%autoreload 2
import scipy as sp
import numpy as np
import matplotlib.pyplot as plt
import mousai as ms
from scipy import pi, sin

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Overview
* A wide array of contemporary problems can be represented by nonlinear ordinary differential equations with solutions that can be represented by Fourier Series
  * Limit cycle oscillation of wings/blades
  * Flapping motion of birds/insects/ornithopters
  * Flagellum (threadlike cellular structures that enable bacteria etc. to swim)
  * Shaft rotation, especially including rubbing or nonlinear bearing contacts
  * *Engines*
  * Radio/sonar/radar electronics
  * Wireless power transmission
  * Power converters
  * Boat/ship motions and interactions
  
 

  * Cardio systems (heart/arteries/veins/)
  * Ultrasonic systems transversing nonlinear media
  * Responses of composite materials or materials with cracks
  * Near buckling behavior of vibrating columns
  * Nonlinearities in power systems
  * Energy harvesting systems
  * Wind turbines
  * Radio Frequency Integrated Circuits
  * **Any system with nonlinear coatings/friction damping, air damping, etc.**
  
These can all be observed in a quick literature search on 'Harmonic Balance'. 

## Why write Mousai?

* The ability to code harmonic balance seems to be publishable by itself
    * It's not research- it's just application of a known technique
* A limited number of people have this knowledge and skill
    * Most cannot access this technique
    * "Research effort" is spent coding the technique, not doing research

## Why write Mousai? (continued)
* Matlab command eig unleashed power to the masses
    * Very few papers are published on eigensolutions- they have to be better than ``eig``
    * ``eig`` only provides simple access to high-end eigensolvers written in ``C`` and ``Fortran``
    * Undergraduates with no practical understanding of the algorithms easily solve problems
    that were intractable a few decades ago.
* *Access* and *ease of use* of such techniques enable *greater science* and *greater research*.
* The real world is nonlinear, but linear analysis dominates because the tools are easier to use.
* With ``Mousai``, an undergraduate can solve a nonlinear harmonic problem easier then a PhD can today (unless they have their own solver!)

In [51]:
def duff_osc_ss(x, params):
    omega = params['omega']
    t = params['cur_time']
    xd = np.array([[x[1]],
                   [-x[0]-.1*x[0]**3-.1*x[1]+1*sin(omega*t)]])
    return xd

In [52]:
t, x, e, amps, phases = ms.hb_so(duff_osc_ss, x0 = np.array([[0,1,-1],[.1,-.1,0,]]), 
                                 omega = 0.1, eqform='first_order', num_harmonics=1)
amps

array([ 0.94593474,  0.09459347])

In [56]:
t, x, e, amps, phases = ms.hb_so(duff_osc_ss, x0 = np.array([[0,1,-1],[.1,-.1,0,]]), omega = .1, eqform='first_order', num_harmonics=5)
amps

array([ 0.94695614,  0.09469561])

In [53]:
amps

array([ 0.94593474,  0.09459347])

In [32]:
t

array([  0.        ,   5.71198664,  11.42397329,  17.13595993,
        22.84794657,  28.55993321,  34.27191986,  39.9839065 ,
        45.69589314,  51.40787979,  57.11986643])

In [6]:
help(ms.hb_so)

Help on function hb_so in module mousai.har_bal:

hb_so(sdfunc, x0=None, omega=1, method='newton_krylov', num_harmonics=1, num_variables=None, eqform='second_order', params={'function': <function duff_osc_ss at 0x107a22730>, 'time': array([  0.        ,   5.71198664,  11.42397329,  17.13595993,
        22.84794657,  28.55993321,  34.27191986,  39.9839065 ,
        45.69589314,  51.40787979,  57.11986643]), 'omega': 0.1, 'n_har': 5, 'cur_time': 57.119866428905333}, realify=True, **kwargs)
    Harmonic balance solver for second order ODEs.
    
    Obtains the solution of a second-order differential equation under the
    presumption that the solution is harmonic.
    
    Returns t (time), x (displacement), v (velocity), and a (acceleration)
    response of a second order linear ordinary differential
    equation defined by
    :math:`\ddot{\mathbf{x}}=f(\mathbf{x},\mathbf{v},\omega)` or
    :math:`\dot{\mathbf{x}}=f(\mathbf{x},\omega)`.
    
    For the state space form, the function `

In [2]:
def two_dof_demo(x, params):
    '''Example from Slater, 1996
    Slater, J. C., “A Numerical Method for Determining Nonlinear Normal Modes,” 
    Nonlinear Dynamics, Vol. 10, May 1996, pp. 19–30.
    Equation (4)'''
    omega = params['omega']
    t = params['cur_time']
    xd = np.array([[x[2]],
                  [-2*x[1]+x[3]],
                  [x[4]],
                  [x[3]-2*x[1]]])
    
    return xd